var folio = require('..');

folio('require.basic')
  .root(__dirname)
  .use(folio.requires())
    .package('basic')
    .dir('./require_basic')
    .entry('./basic.js')
    .pop()
  .use(folio.indent())
    .line('  ')
    .pop()
  .use(folio.wrapper())
    .package('basic')
    .expose("require('basic')")
    .template('amd')
    .pop()
  .use(folio.save())
    .file('./dist/require.basic.js')
    .pop()
  .use(folio.minify())
    .pop()
  .use(folio.save())
    .file('./dist/require.basic.min.js')
    .pop()
  .compile();
